########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
 mariadb_root_password:
    file: $DOCKERDIR/secrets/mariadb_root_password
 nextcloud_admin_password:
    file: $DOCKERDIR/secrets/nextcloud_admin_password
 nextcloud_admin_password:
    file: $DOCKERDIR/secrets/nextcloud_admin_password
 nextcloud_admin_password:
    file: $DOCKERDIR/secrets/nextcloud_admin_password


include:
  ########################### SERVICES
  # HOSTNAME defined in .env file
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/traefik.yml
  # - compose/$HOSTNAME/portainer.yml

